name: github pages

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Fetch private repo
        uses: actions/checkout@v2
        with:
          repository: wncmc/priv
          submodules: true  # Fetch Hugo themes
          #fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          token: ${{ secrets.my_pat }}
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: wncmc/test
          publish_branch: gh_pages
          publish_dir: ./public
          full_commit_message: Update ${{ github.event.head_commit.id }}
